### ISSUE TITLE
compile error 2

### ISSUE THREAD

**Issue by PFQS** [Jmeyer1292/hybrid_planning_experiments#13]
I compile the code according to the tutorial, and I get the error information as follow:

_____________________________________________________________________________
Errors     << opw_kinematics:cmake /home/jiqi/code/test_git/logs/opw_kinematics/build.cmake.002.log
CMake Error at /opt/ros/melodic/lib/cmake/ros_industrial_cmake_boilerplate/cmake_tools.cmake:210 (install):
  install TARGETS given target "DEPENDENCIES" which does not exist in this
  directory.
Call Stack (most recent call first):
  /opt/ros/melodic/lib/cmake/ros_industrial_cmake_boilerplate/cmake_tools.cmake:283 (install_targets)
  CMakeLists.txt:52 (configure_package)

CMake Error: File /home/jiqi/code/test_git/src/opw_kinematics/cmake/opw_kinematics-config.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.10/Modules/CMakePackageConfigHelpers.cmake:312 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /opt/ros/melodic/lib/cmake/ros_industrial_cmake_boilerplate/cmake_tools.cmake:244 (configure_package_config_file)
  /opt/ros/melodic/lib/cmake/ros_industrial_cmake_boilerplate/cmake_tools.cmake:284 (generate_package_config)
  CMakeLists.txt:52 (configure_package)

cd /home/jiqi/code/test_git/build/opw_kinematics; catkin build --get-env opw_kinematics | catkin env -si  /usr/bin/cmake /home/jiqi/code/test_git/src/opw_kinematics --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX=/home/jiqi/code/test_git/devel -DCMAKE_BUILD_TYPE=Release; cd -
...............................................................................
Failed     << opw_kinematics:cmake                          [ Exited with code 1 ]
Failed    <<< opw_kinematics                                [ 0.1 seconds ]    
Abandoned <<< tesseract_msgs                                [ Unrelated job failed ]
Abandoned <<< trajopt_ext                                   [ Unrelated job failed ]
Abandoned <<< trajopt_test_support                          [ Unrelated job failed ]
Abandoned <<< trajopt_utils                                 [ Unrelated job failed ]
Abandoned <<< workcell1_support                             [ Unrelated job failed ]
Abandoned <<< workcell2_support                             [ Unrelated job failed ]
Abandoned <<< workcell3_support                             [ Unrelated job failed ]
Abandoned <<< workcell4_support                             [ Unrelated job failed ]
Abandoned <<< abb_irb1200_gazebo                            [ Unrelated job failed ]
Abandoned <<< abb_crb15000_support                          [ Unrelated job failed ]
Abandoned <<< abb_irb120_support                            [ Unrelated job failed ]
Abandoned <<< abb_irb2400_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb2600_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb4400_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb4600_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb52_support                             [ Unrelated job failed ]
Abandoned <<< abb_irb5400_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb6700_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb7600_support                           [ Unrelated job failed ]
Abandoned <<< abb_irb1200_5_90_moveit_config                [ Unrelated job failed ]
Abandoned <<< abb_irb1200_7_70_moveit_config                [ Unrelated job failed ]
Abandoned <<< abb_irb120_gazebo                             [ Unrelated job failed ]
Abandoned <<< abb_irb120_moveit_config                      [ Unrelated job failed ]
Abandoned <<< abb_irb120t_moveit_config                     [ Unrelated job failed ]
Abandoned <<< abb_irb1600_6_12_moveit_config                [ Unrelated job failed ]
Abandoned <<< abb_irb2400_moveit_config                     [ Unrelated job failed ]
Abandoned <<< abb_irb6640_moveit_config                     [ Unrelated job failed ]
Abandoned <<< industrial_robot_simulator                    [ Unrelated job failed ]
Abandoned <<< fcl_ros                                       [ Unrelated job failed ]
Abandoned <<< simple_message                                [ Unrelated job failed ]
Abandoned <<< industrial_robot_client                       [ Unrelated job failed ]
Abandoned <<< tesseract_collision                           [ Unrelated job failed ]
Abandoned <<< tesseract_ros                                 [ Unrelated job failed ]
Abandoned <<< descartes_light                               [ Unrelated job failed ]
Abandoned <<< tesseract_monitoring                          [ Unrelated job failed ]
Abandoned <<< tesseract_rviz                                [ Unrelated job failed ]
Abandoned <<< trajopt_tools                                 [ Unrelated job failed ]
Abandoned <<< trajopt_sco                                   [ Unrelated job failed ]
Abandoned <<< trajopt                                       [ Unrelated job failed ]
Abandoned <<< tesseract_planning                            [ Unrelated job failed ]
Abandoned <<< trajopt_examples                              [ Unrelated job failed ]
Abandoned <<< hybrid_planning_common                        [ Unrelated job failed ]
Abandoned <<< workcell1_demos                               [ Unrelated job failed ]
Abandoned <<< workcell1_moveit_config                       [ Unrelated job failed ]
Abandoned <<< workcell2_demos                               [ Unrelated job failed ]
Abandoned <<< workcell2_moveit_config                       [ Unrelated job failed ]
Abandoned <<< workcell3_demos                               [ Unrelated job failed ]
Abandoned <<< workcell3_moveit_config                       [ Unrelated job failed ]
Abandoned <<< workcell4_demos                               [ Unrelated job failed ]
Abandoned <<< workcell4_moveit_config                       [ Unrelated job failed ]
Finished  <<< industrial_msgs                               [ 0.7 seconds ]    
Finished  <<< libccd_ros                                    [ 0.6 seconds ]    
Finished  <<< octomap_ros                                   [ 0.6 seconds ]    
Finished  <<< tesseract_core                                [ 1.9 seconds ]    
[build] Summary: 15 of 66 packages succeeded.                                  
[build]   Ignored:   4 packages were skipped or are blacklisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 50 packages were abandoned.                               
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 3.3 seconds total.                                            
[build] Note: Workspace packages have changed, please re-source setup files to use them.

######################################################
I'm not familiar with ROS，could you provide some solution，thanks!

**Comment by Levi-Armstrong** [comment]
All of this functionality has been migrated to the [Tesseract Motion Planning Framework](https://github.com/tesseract-robotics). The [tesseract_ros_examples](https://github.com/tesseract-robotics/tesseract_ros/tree/master/tesseract_ros_examples) would be a good place to start getting familiar along with the [documentation](https://tesseract-docs.readthedocs.io/en/latest/).

Main Repos:
- tesseract
- tesseract_planning
- tesseract_ros

**Comment by PFQS** [comment]
> All of this functionality has been migrated to the [Tesseract Motion Planning Framework](https://github.com/tesseract-robotics). The [tesseract_ros_examples](https://github.com/tesseract-robotics/tesseract_ros/tree/master/tesseract_ros_examples) would be a good place to start getting familiar along with the [documentation](https://tesseract-docs.readthedocs.io/en/latest/).
> 
> Main Repos:
> 
> * tesseract
> * tesseract_planning
> * tesseract_ros

oh,it's so cool ,tanks for your reply!
